server:
  port: 9264
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    com.nodemules.spotify.stats: DEBUG
spring:
  caching:
    time-to-live: 60
  data:
    mongodb:
      uri: mongodb://localhost/spotify-stats