server:
  port: ${PORT:8080}
spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: post
        provider:
          spotify:
            token-uri: https://accounts.spotify.com/api/token