server:
  port: ${PORT}
spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: client_credentials
            client-authentication-method: post
        provider:
          spotify:
            token-uri: https://accounts.spotify.com/api/token
  caching:
    time-to-live: ${SPRING_CACHING_TTL}
feign:
  circuitbreaker:
    enabled: true
application:
  cors:
    allowed-origins:
      - "https://nodemules.github.io"
      - "http://localhost:3000"
