name: Generating Code Coverage

on: [ push, pull_request ]

jobs:
  Generate-Code-Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
          arguments: clean test jacocoTestReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./build/reports/jacoco/test
