name: heroku

on:
  push:
    branches: [ main ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}

jobs:

  deploy:
    name: Deploy to Heroku
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
          arguments: clean build

      - name: Docker Build
        run: docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com

      - name: Docker Publish
        run: |
          heroku container:push web -a $HEROKU_APP_NAME
          heroku container:release web -a $HEROKU_APP_NAME
